version: "3.7"

services:
  guia-peptideos:
    image: guia-peptideos:latest
    build: .
    networks:
      - GustavoSaNet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.guia-peptideos.rule=Host(`dr.gustavosa.com.br`) && PathPrefix(`/guia-peptideos`)
        - traefik.http.routers.guia-peptideos.entrypoints=websecure
        - traefik.http.routers.guia-peptideos.tls.certresolver=letsencryptresolver
        - traefik.http.routers.guia-peptideos.service=guia-peptideos
        - traefik.http.routers.guia-peptideos.middlewares=guia-peptideos-stripprefix
        - traefik.http.middlewares.guia-peptideos-stripprefix.stripprefix.prefixes=/guia-peptideos
        - traefik.http.services.guia-peptideos.loadbalancer.server.port=80
        - traefik.http.services.guia-peptideos.loadbalancer.passHostHeader=true

networks:
  GustavoSaNet:
    external: true
